# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8
      after_success:
        - echo "done"

    - python: 3.6
      #taken from https://quick-sphinx-tutorial.readthedocs.io/en/latest/advanced.html
      branches:
        only:
          - master
      env: test-doc-creation
      sudo: false
      install:
        - python -m pip install -U -r requirements_dev.txt
        - python setup.py install
      script:
        - cd docs; make html
      # Flags used here, not in `make html`:
      #  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
      #  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
      after_success:
        - echo "done"

    - python: 3.6
        #taken from https://quick-sphinx-tutorial.readthedocs.io/en/latest/advanced.html
      branches:
          only:
          - master
      env: test-doc-links
      sudo: false
      install:
      - python -m pip install -U -r requirements_dev.txt
      - python setup.py install
      script:
      - cd docs; make linkcheck
          # Flags used here, not in `make html`:
      #  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
        #  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
      after_success:
      - echo "done"

    - language: python
      sudo: required
      dist: xenial
      python: "3.7"
      env: linux-py37

    - language: generic
      python: 3.6
      env: osx-py36
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py36 python=3.6 -y
      install:
        - source activate py36
        - conda config --add channels conda-forge
        - conda install -y --name py36 tox coveralls
        - pip freeze
      script: tox -e py36

    - language: generic
      python: 3.7
      env: osx-py37
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py37 python=3.7 -y
      install:
        - source activate py37
        - conda config --add channels conda-forge
        - conda install -y --name py37 tox coveralls
        - pip freeze
      script: tox -e py37

  allow_failures:
#      this test is allowed to fail since it uses external resources
    - env: test-doc-links

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: s-weigand
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: s-weigand/work_tracker
#    python: 3.6
